export type LegalPageKey = 'legal' | 'privacy' | 'cookies'
export interface LegalSection { title: string; paragraphs: string[] }
export const legalContent: Record<LegalPageKey, { title: string; intro: string; sections: LegalSection[] }> = {
  legal: {
    title: 'Legal notice',
    intro: 'AI Juicing is a personal home for AI lessons, notes, projects, and experiments shared in public.',
    sections: [
      { title: 'About this website', paragraphs: ['AI Juicing publishes educational videos, written notes, and links to software and other projects. You can browse without creating an account. This website does not offer visitor registration or sign-in. The contact form is for getting in touch about the content, projects, and possible collaborations.'] },
      { title: 'Learning and experimenting', paragraphs: ['The content shares practical experience and ideas for learning. It is general information, not individual professional advice. AI tools can produce inaccurate or incomplete results, and the software and services discussed can change. Check important information and review any code or instructions before using them with your own systems or data.'] },
      { title: 'Content and project ownership', paragraphs: ['Original AI Juicing writing, branding, and media remain the property of their respective rights holders. Linking to this website is welcome. Ask before republishing substantial content or using the branding in a way that suggests endorsement.', 'Projects linked from the directory have their own owners, licenses, and terms. A link to a public repository does not by itself grant an open-source license. Check the license supplied with each project before copying, modifying, or distributing it. Third-party names, logos, and videos belong to their respective owners.'] },
      { title: 'External websites and videos', paragraphs: ['The project directory and other pages link to independent websites, repositories, and YouTube. Those destinations have their own terms and privacy practices. Their inclusion does not guarantee availability, accuracy, security, or suitability for your needs. Embedded YouTube videos are provided by Google, subject to YouTube’s terms.'] },
      { title: 'Availability and responsible use', paragraphs: ['Features, experiments, and articles may be updated or removed. Take appropriate precautions before relying on a tool or example. Do not misuse the contact form, attempt unauthorized access, or disrupt the site. Nothing in this notice excludes rights or responsibilities that cannot lawfully be excluded.'] },
      { title: 'Questions and corrections', paragraphs: ['Please get in touch through the contact page if you spot an error, have a question about using content, or need to raise a rights or privacy concern. Include the relevant page and enough detail to help identify the issue.'] },
    ],
  },
  privacy: {
    title: 'Privacy policy',
    intro: 'This policy explains how information is handled when you browse AI Juicing, use the contact form, or choose to load an embedded video. It covers this website, not the separate projects it links to.',
    sections: [
      { title: 'Browsing without an account', paragraphs: ['You do not need an account to read notes, explore projects, or watch lessons here. AI Juicing has no visitor authentication or registration. When a page is requested, the systems delivering it receive technical information such as the IP address, requested URL, time, and browser details. Hosting and security providers may process this information to deliver the site, diagnose errors, and prevent abuse.'] },
      { title: 'Contact messages', paragraphs: ['If you send a message, the information you enter—such as your name, email address, message, and any other fields you choose to complete—is used to respond and manage the conversation. Please do not include passwords, financial details, or other sensitive information.', 'The contact form is supported by the Growth Engine form service. Information submitted through it may be handled by the form, hosting, and email services used to receive and respond to your request. Sending a contact message is not a request to subscribe to marketing.'] },
      { title: 'Google Analytics', paragraphs: ['AI Juicing uses Google Analytics when analytics is enabled to understand which pages and lessons are useful and how visitors find and use the site. This can include page views, interactions, referral information, browser and device details, approximate location, and identifiers stored in analytics cookies. Google processes this information to produce usage reports.', 'The site’s analytics code does not intentionally send contact-message contents, names, or email addresses as analytics events. Avoid including personal information in URLs you share with the site. See the cookie policy for the current loading behavior and the choices available to you.'] },
      { title: 'Google Search Console', paragraphs: ['Google Search Console is used to understand how the website appears in Google Search, including search queries, impressions, clicks, indexing, and technical issues. These reports concern activity on Google Search and Google’s crawling of public pages. Search Console verification does not itself require a visitor-tracking script or analytics cookies on this website. It does not give AI Juicing access to your Google account or search history.'] },
      { title: 'Embedded YouTube videos', paragraphs: ['Video thumbnails are served by this website. A YouTube player is loaded only after you select a lesson or press a video’s load/play control. The player uses youtube-nocookie.com, YouTube’s privacy-enhanced mode.', 'Loading or playing a video connects your browser to Google/YouTube, which receives technical information such as your IP address, browser details, and the page or video being requested. The player may use cookies or similar storage, particularly when you interact with it. Privacy-enhanced mode limits personalization; it does not eliminate data processing. Google’s privacy policy and YouTube’s terms apply to that player. You can browse the surrounding content without loading a video.'] },
      { title: 'Your display preference', paragraphs: ['If you select Light, Dark, or Auto, the website saves that preference in your browser’s local storage under the key “theme”. It is used to remember the appearance you selected and is not an analytics identifier. You can change it in the footer or remove it by clearing this site’s browser data.'] },
      { title: 'Purposes, providers, and international processing', paragraphs: ['Contact information is used to respond to requests. Technical information supports delivery, troubleshooting, and security. Analytics supports understanding and improving the website. Where data-protection law requires a legal basis, these purposes may rely on responding to steps you request, legitimate interests in operating the site and handling correspondence, legal obligations, or consent where required for optional tracking.', 'Information may be processed by service providers supporting hosting, forms, communications, and Google services. It may also be disclosed where required by law or necessary to address abuse or protect legal rights. Providers may process information outside your country. The protections and transfer arrangements applicable to Google services are described in Google’s privacy documentation.'] },
      { title: 'How long information is kept', paragraphs: ['Contact correspondence is kept for as long as needed to handle the request, follow up on the conversation, and meet any applicable record-keeping or legal requirements. Technical logs follow the hosting and security services’ retention settings. Analytics information follows the configured Google Analytics retention settings; cookie lifetimes are separate from report-data retention. Your theme preference remains in your browser until changed or cleared.'] },
      { title: 'Your choices and rights', paragraphs: ['You can browse without submitting a message and leave embedded videos unloaded. Your browser can block or clear cookies and local storage. Google also offers an Analytics opt-out browser add-on.', 'Depending on the law applicable to you, you may have rights to access, correct, delete, restrict, or receive a copy of your personal information, object to certain processing, or withdraw consent. Withdrawal does not affect earlier lawful processing. Contact AI Juicing to make a request; enough information may be needed to verify the request without collecting unnecessary data. You can also raise a concern with the data-protection authority in your country.'] },
      { title: 'Updates and other websites', paragraphs: ['This policy may be updated as the website changes. The date below identifies the latest revision. When you follow a project, repository, or other external link, the destination’s own privacy policy applies.'] },
    ],
  },
  cookies: {
    title: 'Cookie policy',
    intro: 'Cookies and local storage are small pieces of information saved by your browser. Here is how AI Juicing and its embedded services use them.',
    sections: [
      { title: 'No sign-in cookies', paragraphs: ['AI Juicing does not provide visitor accounts or registration, so it does not use account sign-in cookies for those features. Hosting and security services may still process requests to deliver and protect the website.'] },
      { title: 'Appearance preference: theme', paragraphs: ['The “theme” local-storage entry remembers your Light, Dark, or Auto selection. It is set when you choose an appearance, stays in that browser until changed or cleared, and is not shared as an analytics identifier. Local storage is different from a cookie: the browser does not automatically send it with every page request.'] },
      { title: 'Google Analytics cookies', paragraphs: ['When configured, Google Analytics can use first-party cookies such as “_ga” and “_ga_<identifier>” to distinguish visitors and retain session information. Google documents a default lifetime of two years for these GA4 cookies; the actual lifetime can depend on configuration and browser limits.', 'In the current implementation, a configured Analytics tag loads automatically after the page becomes interactive. There is not yet an on-site analytics consent selector. Browser cookie controls and Google’s Analytics opt-out add-on can limit collection. Blocking cookies does not necessarily prevent every network request to Google.'] },
      { title: 'YouTube: loaded on request', paragraphs: ['The site initially displays a locally hosted thumbnail rather than a YouTube iframe. Choosing a lesson or pressing its load/play control requests the privacy-enhanced YouTube player from youtube-nocookie.com.', 'Once loaded, Google receives connection and player information. Interacting with the player may involve cookies or similar browser storage. The exact storage depends on Google’s player, your browser, and your interaction. Privacy-enhanced mode is not a promise that no cookies or personal data are involved. Leaving the player unloaded avoids that embedded-player connection. Following a “Watch on YouTube” link instead opens YouTube under its own privacy rules.'] },
      { title: 'Google Search Console', paragraphs: ['Search Console is used for search-performance and indexing reports. It does not require a separate visitor cookie on this website. A verification meta tag or DNS record is not an analytics tracker. Google Analytics is a separate service, described above.'] },
      { title: 'Managing browser storage', paragraphs: ['You can inspect, block, or delete cookies and local storage in your browser settings. Clearing site data also clears your saved appearance preference. Restrictions may affect embedded-video features. To learn about Google’s processing or install its Analytics opt-out add-on, use the links below.'] },
    ],
  },
}
